version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:8000

  frontend:
    image: node
    volumes:
      - ./vue_frontend:/app/vue_frontend
    working_dir: /app/vue_frontend
    command: sh -c "npm install && npm run serve"
    ports:
      - 8080:8080