# Generated by Django 4.2.2 on 2023-07-03 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='dia',
            field=models.IntegerField(default=1),
        ),
    ]
