# Generated by Django 4.2.2 on 2023-07-04 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_tarea_dia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
